---
title: "Make_art function"
author: "Britt Kok"
date: '2023-01-27'
output: html_document
---

```{r, include=FALSE}
library(dplyr)
```

The code below defines a function that generates random art in R. The input values are; a number to set the output (for reproducible results), a number used for calculations, and a color palette. 

## Make art function

```{r}
make_art <- function(seed, n, palette) {
  set.seed(seed)
  dat <- tibble(
    x0 = runif(n),
    y0 = runif(n),
    x1 = x0 + runif(n, min = -2, max = 2),
    y1 = y0 + runif(n, min = -4, max = 4),
    shade = runif(n),
    linewidth = runif(n)
  )
  
  # plot segments in various colors, using
  # polar coordinates and a gradient palette
  dat |>
    ggplot(aes(
      x = x0,
      y = y0,
      xend = x1,
      yend = y1,
      colour = shade,
      linewidth = linewidth
    )) +
    geom_segment(show.legend = FALSE) +
    coord_polar() +
    scale_colour_gradientn(colours = palette) +
    scale_size(range = c(0, 10)) +
    theme_void()
}

make_art(
  seed = 1,
  n = 500,
  palette = c("antiquewhite", "orange", "bisque")
)
```